service: aws-sns-usage-example-service

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1
  environment: # log jul over log4j2
    JAVA_TOOL_OPTIONS: -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

package:
  artifact: build/distributions/aws-sns-usage-example.zip

functions:
  entityEvents:
    handler: com.jrestless.aws.examples.RequestHandler
    events:
      - sns: entity-created
      - sns: entity-deleted
