service: aws-gateway-binary-service

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1

package:
  artifact: build/distributions/aws-gateway-binary.zip

functions:
  api:
    handler: com.jrestless.aws.examples.RequestHandler
    events:
      - http:
          path: api/{proxy+}
          method: any
